# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "shell",
      inline: "sudo rm -rf alirem setup.py requirements.txt README.md"
  config.vm.provision "file", source: "../alirem", destination: "alirem"
  config.vm.provision "file", source: "../setup.py", destination: "setup.py"
  config.vm.provision "file", source: "../requirements.txt", destination: "requirements.txt"
  config.vm.provision "file", source: "../README.md", destination: "README.md"
  config.vm.provision "shell",
        inline: "sudo apt -y update && sudo apt install -y python python-pip && sudo pip install setuptools && sudo ./setup.py install --force"
end